[package]
name = "doc_src"
version = "0.1.0"
authors = ["aniketfuryrocks <prajapati.ani306@gmail.com>"]
edition = "2018"
[profile.release]
lto = true

[dependencies]
wee_alloc = "0.4.5"

[dependencies.gxi]
version = "0.4.0"
features = ["web"]
